// <auto-generated />
using System;
using FakeBilibili.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FakeBilibili.Migrations.UserAndVideoDb
{
    [DbContext(typeof(UserAndVideoDbContext))]
    partial class UserAndVideoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FakeBilibili.Models.DomainModels.User", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("AvatarLocation");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Fans");

                    b.Property<string>("Follows");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FakeBilibili.Models.DomainModels.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<int>("Category");

                    b.Property<TimeSpan>("Duration");

                    b.Property<DateTime>("PublishDateTime");

                    b.Property<string>("Tag");

                    b.Property<string>("ThumbnailLocation")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("VideoLocation")
                        .IsRequired();

                    b.Property<int>("VideoView");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("FakeBilibili.Models.DomainModels.Video", b =>
                {
                    b.HasOne("FakeBilibili.Models.DomainModels.User", "Author")
                        .WithMany("Works")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
